name: CI Pipeline with ArgoCD Deployment

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          pip install pytest
          pip install -r Code/controller/requirements.txt

     # - name: Run Unit Tests
     #   run: pytest Code/controller/tests/

  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Controller Image
        run: |
          docker build -t flickerbot/controller:latest -f Code/controller/Dockerfile Code/controller
          docker push flickerbot/controller:latest

  #update-helm:
   # name: Update Helm Chart for ArgoCD
   # runs-on: ubuntu-latest
   # needs: build-and-push
   # steps:
   #   - name: Checkout Code
   #     uses: actions/checkout@v3

    #  - name: Update Image Tag in Helm Chart
   #     run: |
   #       sed -i 's|image: .*|image: <your-dockerhub-username>/custom-controller:latest|' helm-chart/values.yaml
   #       git config user.name "github-actions[bot]"
   #       git config user.email "github-actions[bot]@users.noreply.github.com"
   #       git add helm-chart/values.yaml
   #       git commit -m "Update custom-controller image tag to latest"
   #       git push origin main
